version: '3'
services: 
  web: 
    image: cr.bcx.zone/bcx-docker/chassis/base:v1.7
    volumes: 
      - .:/srv/www
    ports: 
      - 80:80
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - ./storage/app/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tweets
      MYSQL_USER: tweets
      MYSQL_PASSWORD: secret